config/routes.rb
AllianceNetwork::Application.routes.draw do
  resources :users

  resources :sessions,    :only => [:new, :create, :destroy]
  resources :microposts,  :only => [:create, :destroy]
  resources :authentications

  match '/register',  :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  match '/about',     :to => 'pages#about'
  match '/dashboard', :to => 'users#dashboard'
  
  match '/auth/:provider/callback' => 'authentications#create'
  
  root :to => "pages#home"

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentications = current_user.authentications if current_user
  end

  def create
    omniauth = request.env["rack.auth"]
    # OMNIAUTH-SIGNIN
    # Check to see if an authentication already exists, if one does, sign in the appropriate user.
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in via #{authentication.provider}!"
      sign_in(authentication.user)
      redirect_to dashboard_path
    
    # Otherwise, if the user is signed in, create the authentication.
    elsif current_user
      current_user.authentication.create(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful!"
      redirect_to authentications_url
    
    # If this is a new user, redirect them to sign in
    # I want users to be required to have an account with my app before setting up authentications
    # with other sites (Twitter, Facebook, etc.)
    else
      flash[:notice] = "You must be signed in to access this page."
      redirect_to signin_path
    end
      
    # Using find_or_create_by_provider_and_uid it prevents duplicate records in the
    # authentications database should a user try to authenticate with the same service and info.
    # Assumes the user is already signed in to my app
    # 
    # current_user.authentications.find_or_create_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    # flash[:notice] = "Authentication successful!"
    # redirect_to authentications_url
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end

end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/create.html.erb
<h1>Authentication#create</h1>
<p>Find me in app/views/authentication/create.html.erb</p>

app/views/authentications/destroy.html.erb
<h1>Authentication#destroy</h1>
<p>Find me in app/views/authentication/destroy.html.erb</p>

app/views/authentications/index.html.erb
<h1><%= current_user.username %>'s Authentications</h1>

<table>
    <th>User</th>
    <th>Provider</th>
    <th>UID</th>
    <th>Meta</th>
  <% @authentications.each do |auth| %>
  <tr>
    <td><%= auth.id %></td>
    <td><%= auth.provider %></td>
    <td><%= auth.uid %></td>
    <td><%= link_to "Delete", authentications_path(auth.uid), :method => :delete,
                                     :confirm => "Are you sure you want to delete this authentication?",
                                     :title => "Delete #{auth.provider} Authentication" %></td>
  </tr>
  <% end %>
</table>