config/routes.rb
AllianceNetwork::Application.routes.draw do
  resources :users

  resources :sessions,    :only => [:new, :create, :destroy]
  resources :microposts,  :only => [:create, :destroy]
  resources :authentications

  match '/register',  :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  match '/about',     :to => 'pages#about'
  match '/dashboard', :to => 'users#dashboard'
  
  match '/auth/:provider/callback' => 'authentications#create'
  
  root :to => "pages#home"

end

app/models/user.rb
# == Schema Information
# Schema version: 20110307204855
#
# Table name: users
#
#  id                 :integer(4)      not null, primary key
#  username           :string(255)
#  first_name         :string(255)
#  last_name          :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean(1)
#

require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password, :update_type
  attr_accessible :username, :first_name, :last_name, :email, :password, :password_confirmation
  
  has_many :microposts, :dependent => :destroy
  has_many :authentications
  
  username_format = /^[A-Za-z0-9_-]+$/
  
  # For some reason, this regex won't pass the rspec test, though it works fine accord to Rubular
  email_format = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]{2,6}\z/i
  
  validates_presence_of   :username, :first_name, :last_name, :email
  validates :username,    :length => { :maximum => 30 },
                          :format => { :with => username_format },
                          :uniqueness => { :case_sensitive => false }
  validates :first_name,  :length => { :maximum => 50 }
  validates :last_name,   :length => { :maximum => 50 }
  validates :email,       :format => { :with => email_format },
                          :uniqueness => { :case_sensitive => false }
  validates :password,    :length => { :within => 4..18 },
                          :confirmation => true,
                          :presence => true,
                          :if => :noexist_or_update_password
                                                      
  before_save :encrypt_password, :if => :noexist_or_update_password
  
  def feed_status
    Micropost.where("user_id = ?", id)
  end
  
  def status
    # If user has no status updates, set status to blank.
    # Not efficient, but will suffice for now.
    if last_status.nil?
      status = ' '
    else
      last_status.content
    end
  end
  
  def has_password?(submitted_password)
    self.encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(uname, pass)
    user = find_by_username(uname)
    user && user.has_password?(pass) ? user : nil
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def update_attributes_nosave(attributes)
    attributes.each do |key, value|
      self.send("#{key}=", value)
    end
  end

  private
    # Returns true if the user is issuing a password change request specifically (WIP)
    # or if the user doesn't already have a password (as is the case when creating a user).
    def noexist_or_update_password
      !self.respond_to?(:encrypted_password) || self.encrypted_password.nil?
    end
    
    def last_status
      Micropost.where("user_id = ?", id).first
    end
    
    def encrypt_password
      self.salt = salted if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      s_hash("#{salt}--#{string}")
    end
    
    def salted
      s_hash("#{Time.now.utc}--#{password}")
    end
    
    def s_hash(string)
      Digest::SHA2.hexdigest(string)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:new, :create]
  before_filter :correct_user_or_admin, :only => [:edit, :update]
  before_filter :admin_user, :only => [:destroy]
  before_filter :defer, :only => [:new, :create]
  
  def show
    @user = User.find(params[:id])
    @micropost = Micropost.new
    @title = "#{@user.username}'s Profile"
    
    # Loads all of a user's status updates to instance variable
    @status_feed = current_user.feed_status
    
    # Sets the hold location to this page so that when a user updates
    # his status, they will be returned to this page.
    # This will be replaced with a better method (most likely AJAX) later
    hold_location if current_user?(@user)
  end
  
  def index
    @title = "All Users"
    @users = User.all
  end
  
  def dashboard
    @title = "Dashboard"
    @status_feed = Micropost.all
  end
  
  def new
    @title = "Register"
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
      flash[:success] = "Welcome to the Alliance Network!"
      redirect_to @user
    else
      @title = "Sign up"
      # Clear submitted password fields and render the sign-up form.
      @user.password = ""
      @user.password_confirmation = ""
      render 'new'
    end
    
  rescue ActiveRecord::StatementInvalid
    flash[:error] = "There was a problem submitting your registration. Please try again later."
    redirect_to root_path
  end
  
  def edit
    @title = "Edit User"
  end
  
  def update
    @user.update_attributes_nosave(params[:user])
    if @user.save
      flash[:success] = "Profile updated succesfully!"
      redirect_to @user
    else
      @title = "Edit Profile"
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if current_user?(@user)
      redirect_to users_path, :notice => "Admins can't delete themselves!"
    else
      @user.destroy
      flash[:success] = "User \"#{@user.username}\" destroyed."
      redirect_to users_path
    end
  end
  
  private
    # Might be needed later...
    #
    # def clean_params(params_hash)
    #   params_hash.delete(:update_type)
    # end

    def correct_user_or_admin
      @user = User.find(params[:id])
      redirect_to root_path unless current_user.admin? || current_user?(@user)
    end
  
    def admin_user
      redirect_to root_path unless current_user.admin?
    end

    def defer
      redirect_to current_user if signed_in?
    end
    
    # Stores the url of the page user is attempting to view within a session variable
    def hold_location
      session[:return_to] = request.fullpath
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_for(user, options = { :size => 150 })
    gravatar_image_tag(user.email.downcase, :alt => user.username,
                                            :class => 'avatar',
                                            :gravatar => options)
  end
end

app/views/users/_fields.html.erb
<div class="field">
  <%= f.label :username %><br />
  <%= f.text_field :username %>
</div>
<br />
<div class="field">
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name %>
</div>
<div class="field">
  <%= f.label :last_name %><br />
  <%= f.text_field :last_name %>
</div>
<br />
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<br />
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirm Password" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_status_feed.html.erb
<% unless @status_feed.empty? %>
  <% @status_feed.each do |status| %>
    <tr>
      <td>
        <span class="loud"><b><%= status.user.username %></b> </span>
        <%= status.content %>
        <span class="quiet"><%= time_ago_in_words(status.created_at) %> ago</span>
      </td>
      <% if current_user?(status.user) || current_user.admin? %>
      <td>
        <%= link_to "delete", status, :method => :delete,
                                         :confirm => "Are you sure?",
                                         :title => status.content %>
      </td>
      <% end %>
    </tr>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td style="width: 25px !important; text-align: center;"><%= avatar_for(user, :size => 25 )%></td>
  <td><%= link_to user.username, user %></td>
  <td><%= user.first_name %></td>
  <td><%= user.last_name %></td>
  <td><%= user.email %></td>
  <% if current_user.admin? %>
  <td>
    <%= link_to "Edit", edit_user_path(user.id) %> 
    <%= link_to "Delete", user_path(user.id), :method => :delete,
                                     :confirm => "Are you sure you want to delete #{user.username}?",
                                     :title => "Delete User" %>
  </td>
  <% end %>
</tr>

app/views/users/dashboard.html.erb
<h2>Dashboard</h2>
<%= avatar_for(current_user) %>
<p>Welcome <%= current_user.username %>!</p>

<table>
  <th>Recent Activity</th>
  <%= render 'status_feed' %>
</table>

app/views/users/edit.html.erb
<h1>Edit <%= @user.username %>'s Profile</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <br />
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <br />
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <br />
  
  <div class="action">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<br />

<table>
  <th colspan="2">Username</th>
  <th>First Name</th>
  <th>Last Name</th>
  <th>Email</th>
  <% if current_user.admin? %>
  <th>Meta</th>
  <% end %>
  
  <%= render @users %>
</table>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %> 
<% if current_user?(@user) %>
  ( <%= link_to "Edit", edit_user_path %>
    <% if current_user.admin? %>
      | <%= link_to "Delete", user_path, :method => :delete,
                                         :confirm => "Are you sure you want to delete #{@user.username}?",
                                         :title => "Delete User" %>
    <% end %> )
<% end %></h2>

<table>
  <tr>
    <td width="100">
      <%= avatar_for(@user) %>
    </td>
    <td>
      <p>
        <span class="loud">Name: </span><%= @user.first_name %> <%= @user.last_name %><br />
        <span class="loud">Email: </span><%= @user.email %><br />
        <% unless @user.microposts.empty? %><span class="loud">Status: </span><%= @user.status %><% end %>
        
        <% if current_user?(@user) %>
          <%= render 'shared/micropost_form' %>
        <% end %>
      </p>
    </td>
  </tr>
</table>

<table summary="Posts by <%= @user.username %>">
  <th colspan="2">Update History</th>
  <% if @user.microposts.empty? %>
  <tr><td>No Status Updates Found</td></tr>
  <% else %>
    <%= render 'status_feed' %>
  <% end %>
</table>