config/routes.rb
AllianceNetwork::Application.routes.draw do
  resources :users

  resources :sessions,    :only => [:new, :create, :destroy]
  resources :microposts,  :only => [:create, :destroy]
  resources :authentications

  match '/register',  :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  match '/about',     :to => 'pages#about'
  match '/dashboard', :to => 'users#dashboard'
  
  match '/auth/:provider/callback' => 'authentications#create'
  
  root :to => "pages#home"

end

app/views/layouts/_header.html.erb
<header>
  <div class="span-24 last header prepend-top">
    <h1>The Alliance Network</h1>
  
  <nav>
      <h4><%= render 'layouts/navigation' %></h4>
  </nav>
  </div>
</header>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <% if signed_in? %>
    <li class="first"><%= link_to "Dashboard", dashboard_path, :class => "quiet" %></li>
  <% else %>
    <li class="first"><%= link_to "Home", root_path, :class => "quiet" %></li>
  <% end %>
  
  <li><%= link_to "About", about_path, :class => "quiet" %></li>
  
  <% if signed_in? %>
    <li><%= link_to "Members", users_path, :class => "quiet" %></li>
    <li><%= link_to "Logout", signout_path, :class => "quiet" %></li>
  <% else %>
    <li><%= link_to "Register", register_path, :class => "quiet" %></li>
    <li><%= link_to "Sign In", signin_path, :class => "quiet" %></li>
  <% end %>
</ul>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'alliance', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
</head>
<body>

<div class="container">
  <%= render 'layouts/header' %>
  
  <div class="span-24 last" style="margin-top: 25px">
    <section>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, :class => "flash #{key}") %>
        <br />
      <% end %>
    </section>
  </div>
  <br />
  <div class="span-22 push-1">
        <section>
      <%= yield %>
    </section>
  </div>
  
  <% if Rails.env.development? %>
    <div class="span-24 last">
      <%= debug(params) %>
    </div>
  <% end %>
  
</div>

</body>
</html>